### ISSUE TITLE
Unable to create a key pair in automation with no passphrase

### ISSUE THREAD

**Issue by scott1138** [PowerShell/openssh-portable#437]
When running:
`ssh-keygen -t rsa -b 2048 -f 'key_name' -q -N ''`
I receive the error:
`option requires an argument -- N`
This same command works in bash.  Expected result is a key pair with no passphrase.

**Comment by bagajjal** [comment]
on a powershell windows it looks like this,

![image](https://user-images.githubusercontent.com/23668037/77973505-415ee900-72a9-11ea-9899-be6ac5fc2ac6.png)

**Comment by bagajjal** [comment]
BTW, issues are tracked in a different repo https://github.com/powershell/Win32-OpenSSH.

**Comment by fatso83** [comment]
You should remove the possibility to create issues in this repo. It's possible to restrict to pull requests only.
