### ISSUE TITLE
No Microsoft Built Binaries for Release Versions for Downlevel Clients

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/openssh-portable#443]
@joeyaiello - I figured out what I was trying to express on the PS call this last week.

This old repo is doing binary builds and packages of BETA versions of openssh: https://github.com/PowerShell/Win32-OpenSSH - it was the original source of the chocolatey package.

The readme there now points to this repo I am doing this issue from, but this repo only releases source code: https://github.com/PowerShell/openssh-portable/releases/tag/v8.1.0.0

So the problem is that there appears to be no way to get:
1. microsoft compiled binaries
2. for production releases
3. to service downlevel clients

Consequently the Chocolatey package (and anyone else?) is stuck at the last beta.

Unless there is somewhere else entirely to get them?

Here is my prior attempt to get this resolved: https://github.com/PowerShell/Win32-OpenSSH/issues/1578

**Comment by bagajjal** [comment]
@DarwinJS - We release for all supported windows OS versions (Win7 and up) in https://github.com/PowerShell/Win32-OpenSSH. win32-OpenSSH repo is used for issue tracking and microsoft compiled binary releases. Chocolatey can still refer to Win32-OpenSSH for newer releases.

This repo (OpenSSH-Portable) is used for source code and pull requests.

I will make sure the release name on both the repos be consistent for future releases.

**Comment by twangboy** [comment]
This is now a problem as Binaries are no longer being built at https://github.com/PowerShell/Win32-OpenSSH
