### ISSUE TITLE
sshrc for windows

### ISSUE THREAD

**Issue by bkotch** [PowerShell/openssh-portable#444]
Not really an issue so much as a question that I can't find the answer to after combing the internet. 

Where do I create the windows equivalent of ```/etc/ssh/sshrc``` ? 

Right now, I am getting by with the ForceCommand directive in the sshd_config in __PROGRAMDATA__/ssh/administrators_authorized_keys but that feels hack-y. 

Thanks in advance.

**Comment by bagajjal** [comment]
sshrc is currently not supported on windows. 
Using forceCommand is one way to achieve this functionality.

We track our issues in https://github.com/PowerShell/Win32-OpenSSH/ repo. Please open a new issue under win32-openssh.
