### ISSUE TITLE
How to make ssh not give admin rights by default

### ISSUE THREAD

**Issue by greggman** [PowerShell/openssh-portable#445]
From cmd.exe I start pwsh

```
Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\gregg>pwsh
PowerShell 7.0.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

Loading personal and system profiles took 620ms.
❯ (New-Object Security.Principal.WindowsPrincipal(
>>   [Security.Principal.WindowsIdentity]::GetCurrent())
>> ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
False
```

From cmd.exe I ssh to localhost

```
Microsoft Windows [Version 10.0.18363.900]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\gregg>ssh localhost
gregg@localhost's password:
PowerShell 7.0.1
Copyright (c) Microsoft Corporation. All rights reserved.

https://aka.ms/powershell
Type 'help' to get help.

Loading personal and system profiles took 620ms.
❯ (New-Object Security.Principal.WindowsPrincipal(
>>   [Security.Principal.WindowsIdentity]::GetCurrent())
>> ).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
True
```

For some magic reason when I ssh to pwsh I get admin but when I open locally I don't. 

Is there a way to get those to situations to be the same as they would on MacOS or Linux? Even my user account has admin rights I'd like not to automagically get those rights just by using ssh.

**Comment by bagajjal** [comment]
@greggman - ssh doesn't give admin right by default to all.

Admin users will get elevated prompt. This is true for any network logins (powershell remoting over winrm) as there is no way for us to display a prompt for elevated sessions.

For non-admin users will not get any admin privileges.

**Comment by bagajjal** [comment]
Please open new issues at https://github.com/PowerShell/Win32-OpenSSH/issues.
