### ISSUE TITLE
Allow client to open graphical user interface programs in the server

### ISSUE THREAD

**Issue by gabrielmagno** [PowerShell/openssh-portable#448]
**"OpenSSH for Windows" version**
7.7.2.3
 
**Server OperatingSystem**
Windows 10 Pro

**Client OperatingSystem**
Windows 10 Pro

**What is failing**
When I'm logged in the server (no matter the client, I even tried using the same computer as server and client) and try to open a graphical program, it will not open it.

For instance, if I open a local (no SSH) PowerShell and try the following commands, all of them will work and open the respective programs:
- `explorer`
- `mspaint`
- `notepad`

But, if I login in the same computer through SSH, and try the same programs, they will not open, except for the `explorer` that will actually work and open its respective window.

I even tried other programs like Firefox using their fullpath:
- `"C:\Program Files\Mozilla Firefox\firefox.exe"`
- `Start-Process spotify`

All of them will open in a local PowerShell, but will not open acessing the PowerShell through SSH. I also tried `cmd` as the prompt for the SSH session, but it had the same behavior as the PowerShell.

**Expected output**
The program and its respective window to open in the server.

**Actual output**
The program is not started and no window is opened in the server.

**Comment by bagajjal** [comment]
@gabrielmagno - This is expected. You can't launch the windows application when you are connected using SSH / WinRM.

**Comment by gabrielmagno** [comment]
@bagajjal Thank you for the response!

Why is the `explorer` allowed to be launched and not other applications?

Is there any way to circumvent this, and allow to launch windows applications using SSH?

**Comment by bagajjal** [comment]
@gabrielmagno - SSH client renders the UI for only x11 applications. x11 applications exist only on *nix platforms not on windows.
x11 applications will have two parts UI application and the core application. UI application is responsible for just displaying the UI and reading the input like mouse event, keyboard events and sending it back to the core application. core application will decide how to take necessary action / render the UI and then instructs the UI application to act according. ssh client need to host a x11 server that hosts the UI application on client side.

Regarding your question of why explorer is allowed to launch, I have to debug why it's behaving differently. Even in this case the explorer window is displayed on the server but not on client which is useless. There is no way for windows applications to launch over SSH as windows applications are not x11 based.

**Comment by gabrielmagno** [comment]
@bagajjal maybe I was not clear enough, but I was not referring to opening the Windows application in the _client_, but opening it on the _server_ itself. 

My use case is that I want to set an SSH Server in my Windows desktop, so that I can remotely launch these applications in the desktop/server.

**Comment by bagajjal** [comment]
@gabrielmagno - You can start but you can't see. The started windows applications will be in session 0.
![image](https://user-images.githubusercontent.com/23668037/86042028-6d4e4f80-b9fb-11ea-8c39-706eb7fb540b.png)

**Comment by gabrielmagno** [comment]
@bagajjal Oh, I missed that. Thank you!

Is there any way to make the process start in Session 1?

I heard about `PsExec` (https://docs.microsoft.com/pt-br/sysinternals/downloads/psexec), but was wondering if there were other more appropriate ways to do that.

**Comment by bagajjal** [comment]
@gabrielmagno - That is a specific ask. We only support spawning processing in session 0.

**Comment by mtsr** [comment]
That's a shame.

An example use case: In the case of VS Code remote development on a windows host running sshd, it would be really useful. One could have the debugger in the local VS Code connected to a remote GUI application, which can then be controlled in an RDP session. Instead one now has to run a second VS Code in the RDP session and launch debugging sessions there.

Edit: PsExec doesn't work as a workaround, since it breaks many GUI applications, even something like notepad.

**Comment by bagajjal** [comment]
@mtsr - You need to understand that it's out of SSH protocol.
SSH protocol support launching **ONLY** x11 based GUI applications.
Windows GUI applications are not x11 applications. 

If you want VS Code to launch remotely then you have to take this request to VS Code team to make it an x11 application.

**Comment by bagajjal** [comment]
fyi, Windows OpenSSH already supports launching x11 GUI applications..

**Comment by gabrielmagno** [comment]
Just to be clear on my request, I was wondering about opening a GUI application in the host/server, without the necessity of displaying it on the client. I simply wanted to remotely open/execute something on the server. Not sure if @mtsr also needed the application to display on the client.

**Comment by mtsr** [comment]
@bagajjal You're misunderstanding what I'm saying. I want to be able to launch the debugger against an application that just attaches to Session 1 or whatever the RDP session is. Of course it doesn't do X11 forwarding over SSH. But having the Debugger and terminal in the client instead of the remote host would be a big big win.

Exactly what @gabrielmagno wants, apparently.

**Comment by bagajjal** [comment]
Adding to the backlog.

**Comment by bagajjal** [comment]
@gabrielmagno , @mtsr - One of  you please open the issue at https://github.com/PowerShell/Win32-OpenSSH/issues and link this issue. We track the issues in a different repo.
