### ISSUE TITLE
ctrl+c closes SSH session when using X11 forwarding.

### ISSUE THREAD

**Issue by ghost** [PowerShell/openssh-portable#450]
When using X11 forwarding ctrl+c will close the SSH connection instead of just stopping a running program such as 'ping'.  When not using X11 forwarding or if X11 forwarding is not correctly established this behavior is not seen.

# Environment
Platform = Win32NT
Version = 10.0.19041.0
Version String = Microsoft Windows NT 10.0.19041.0
Windows Terminal Version = 1.0.1811.0
SSH Version = OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5

# Steps To Reproduce

1. Install/Run X11 Server (VcXsrv/X410/Xming)
2. Start CMD/Powershell/pwsh (behavior is the same in all 3).
3. Set "DISPLAY" environmental variable
4. SSH with X11 forwarding `ssh -Y user@linuxserver` (adding '-t' won't change behavior)
5. Verify Forwarding is correctly established (run 'xclock' or something)
6. Run `ping 8.8.8.8`
7. use 'ctrl+c' to stop ping

# Expected Behavior 

The 'ping' program should get killed and the terminal should return to the remote shell prompt.

# Actual Behavior

The SSH session gets immediately closed.

`ssh -t -Y -vvv cstation`
![image](https://user-images.githubusercontent.com/67171190/87339733-48320480-c504-11ea-8423-4d6180a19ab5.png)

SSH Establishing Connection Output: 
[debug.txt](https://github.com/PowerShell/openssh-portable/files/4914428/debug.txt)

**Comment by bagajjal** [comment]
Please create new issue at https://github.com/PowerShell/Win32-OpenSSH/issues
