### ISSUE TITLE
ssh-keygen not working in powershell ISE

### ISSUE THREAD

**Issue by jkcapoeira** [PowerShell/openssh-portable#454]
When running ssh-keygen.exe from Windows Powershell ISE it shows the line
Generating public/private rsa key pair, 
but doesn't continue or ask for input where to save the file. 
Running it as normal user and in a session as 'Administrator' in powershell doesn't make a difference. Using win2016.
When i run the command from cmd.exe it works fine.

**Comment by bagajjal** [comment]
Please create new issue at https://github.com/PowerShell/Win32-OpenSSH/issues
