### ISSUE TITLE
How to restrict OpenSSH max logins per user in Windows 10 Home Edition?

### ISSUE THREAD

**Issue by dinohsu1019** [PowerShell/openssh-portable#455]
I have a Windows 10 Home Edition box with a GPU to share via SSH (more specifically sharing go/igo/baduk/weiqi AI engines) , both client program and server program are working fine, the only thing is I don't know is how to restrict the max logins or SSH sessions per user. If one person connects to the server in multiple sessions, the server can be overwhelmed.

I see in Linux there's a MaxLogins option is the limits.conf file, but not sure about OpenSSH in Windows 10. Alternatively, maybe restricting the user to log in multiple times is also an option, but still I am not sure how to do this. I am willing to upgrade the Home Edition to Pro Edition, if it solves my problem.

**Comment by bagajjal** [comment]
Please open the issues at https://github.com/PowerShell/Win32-OpenSSH/issues
