### ISSUE TITLE
Cannot login into msys environment

### ISSUE THREAD

**Issue by ghost** [PowerShell/openssh-portable#456]
MSYS starts its shell with "msys2_shell.cmd -mingw64". I was not able to get Windows/OpenSSH (as a server) to simply login to the same environment. I tried various registry changes, which did change the loigin shell, but never managed to enter the same environment as by the aforementioned command successfully.

OpenSSH was installed via the "Windows optional feature" thing. I'm not sure if it maps to the work in this repository, but information about this is scarce and the GUI is spartan.

I think logging in to msys is a common use case, and there should be first class support for it. My problem is that it does not even seem to work with registry hacking.

**Comment by bagajjal** [comment]
We track issues in a different repo (https://github.com/PowerShell/Win32-OpenSSH/). You can look at the existing issue, if none of them cover your case then open a new issue in Win32-openssh repo.

Please share client side logs (ssh -vvv user@ip) and server side logs (sshd.log with DEBUG3 enabled).
You need to enable the file based logging by following instructions [here](https://github.com/PowerShell/Win32-OpenSSH/wiki/Logging-Facilities).
