### ISSUE TITLE
Login denied if computer name and username are the same

### ISSUE THREAD

**Issue by g-stefan** [PowerShell/openssh-portable#458]
OS: Windows 10 2004 (latest version, all updates)
openssh version:  8.1.0.0

If the computer name is the same as user name openssh gives invalid login, in logs show as unrecognized user!
After changed computer name, login goes well!
This is particular case, will be nice to be able to have that option.

**Comment by bagajjal** [comment]
@g-stefan - This is a known issue. fyi, we track the issues https://github.com/PowerShell/Win32-OpenSSH/issues.
