### ISSUE TITLE
Authentication fails and is very instable

### ISSUE THREAD

**Issue by tomko80** [PowerShell/openssh-portable#459]
I have installed the OpenSSH server feature on a Windows server 2019 machine and configured to work with a local user group, not allow tty access and close the users into a specific folder space.

I'm currently experiencing that 2/3 times I try to access the host using WinSCP the sign in fails. Often I get prompted for the password by the client even if it has not changed, sometimes the sign in process hangs completely and a couple of times the session has escaped the chrootdirectory.

What is going wrong here?

When the authentication fails I see this in the logs (lada is the name of the user, sshclients is the local windows group):

```
17836 2020-08-17 16:15:27.109 debug2: parse_server_config: config reprocess config len 533
17836 2020-08-17 16:15:27.109 debug3: checking match for 'Group administrators' user lada host XXXXXXXX addr XXXXXXXX laddr YYYYYYYY lport 22
17836 2020-08-17 16:15:27.109 debug3: **LsaLogonUser Succeeded (Impersonation: 0)**
17836 2020-08-17 16:15:27.109 debug1: user  does not match group list administrators at line 87
17836 2020-08-17 16:15:27.109 debug3: match not found
17836 2020-08-17 16:15:27.109 debug3: checking match for 'Group sshclients' user  host XXXXXXXX addr XXXXXXXXX laddr YYYYYYYY lport 22
17836 2020-08-17 16:15:27.109 debug3: **get_passwd: Invalid account type: 3.**
17836 2020-08-17 16:15:27.109 debug1: Can't match group at line 91 because user  does not exist
17836 2020-08-17 16:15:27.109 debug3: match not found
```

The expected behavior would be as follows:

```
15376 2020-08-17 16:43:28.473 debug3: checking match for 'Group administrators' user lada host XXXXXXXXX addr 172.20.19.67 laddr YYYYYYYY lport 22
15376 2020-08-17 16:43:28.489 debug3: **LsaLogonUser Succeeded (Impersonation: 0)**
15376 2020-08-17 16:43:28.489 debug1: user lada does not match group list administrators at line 87
15376 2020-08-17 16:43:28.489 debug3: match not found
15376 2020-08-17 16:43:28.489 debug3: checking match for 'Group sshclients' user lada host XXXXXXXX addr XXXXXXXX laddr YYYYYYYYY lport 22
15376 2020-08-17 16:43:28.489 debug3: **LsaLogonUser Succeeded (Impersonation: 0)**
15376 2020-08-17 16:43:28.489 debug1: user lada matched group list sshclients at line 91
15376 2020-08-17 16:43:28.489 debug3: match found
15376 2020-08-17 16:43:28.489 debug3: reprocess config:92 setting ChrootDirectory D:\\Lada
15376 2020-08-17 16:43:28.489 debug3: LsaLogonUser Succeeded (Impersonation: 0)
```

Looks to me the user details get lost on the way.

The configuration looks like this:

```
PermitEmptyPasswords no
PermitTTY no
PermitTunnel no 
AllowAgentForwarding no 
AllowTcpForwarding no
X11Forwarding no 

ForceCommand internal-sftp 
Subsystem  sftp   sftp-server.exe -d "D:\Lada\" 

AllowGroups sshclients Administrators

Match Group administrators
       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys

#Match User lada
Match Group sshclients
ChrootDirectory D:\Lada
```

You can find the full logs and configs [here](https://andritz-my.sharepoint.com/:f:/p/tom_kostiainen/ErAo3jj4MtVKnuxa-rHrvpEBlD7oixxSdVoZMjpg7vwtSw?e=mR8LKp).

**Comment by NoMoreFood** [comment]
@tomko80 We revised much of the authentication process to be more robust since the version that was included in Server 2019 (7.7).   Please try reinstalling the latest version and reproducing the issue.

https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH

**Comment by tomko80** [comment]
@NoMoreFood thanks for the comment, I uninstalled the version available from "optional features" and did the manual install. Seems to work at the moment, will continue testing a while and then close.

The old config worked fine, but I'm now not getting any logs under /ssh/logs, has there been a change to this?

**Comment by tomko80** [comment]
Updating fixed the problems with the authentication. I wonder why such an invalid version is still pushed through the standard windows update?
