### ISSUE TITLE
Bad owner or permissions on C:\\Users\\[USER]/.ssh/config

### ISSUE THREAD

**Issue by williamtrelawny** [PowerShell/openssh-portable#461]
**OS:** Microsoft Windows [Version 10.0.19041.508]
**PS version:** 7.0.3

With no $USERHOME/.ssh/config file present, ssh works fine.

With a user-created config file, when attempting to ssh to a local network host, Windows throws the error "Bad owner or permissions on C:\\Users\\Falco/.ssh/config".

However, if I pass the config file location via the -F flag, ssh works fine and uses the parameters within the config file, which indicates this cannot actually be a permissions issue on the $USERHOME/.ssh folder or the config file within.

Example:
```
PS C:\Users\Falco> ssh graylog.lab
Bad owner or permissions on C:\\Users\\Falco/.ssh/config

PS C:\Users\Falco> ssh graylog.lab -F C:\Users\Falco\.ssh\config
Last login: Wed Sep  9 10:11:02 2020 from falco.home
[mithos@graylog ~]$
```

I have a feeling it has something to do with the strange config file path it generates by default when no -F flag is present. I've seen other threads with this similar issue, including the bugfix #418 where the PC name and user name being the same caused a conflict. This is my case (PC name and User name are both "Falco"), however I've done a fresh install of Powershell since this bugfix was released so I assume my build has the fix. Sorry, but I can't figure out how to tell what version a pull request was merged into so I can't say for sure. All I know is that #418 was merged 12/16/19 and I did a complete Windows 10 wipe & reinstall back in June 2020.

Another thing to note - I don't use the "Falco" local account to login anymore, I use my Microsoft account. These are somehow tied together though, because in the permissions system the user FALCO/Falco resolves to my MS Account email address. Not sure if that's relevant or not, but it's a factor no one else has mentioned thus far.

**Comment by bagajjal** [comment]
Please check the issues at https://github.com/PowerShell/Win32-OpenSSH/issues. Open a new issue if it's not already there.
fyi, this github repo is only for code.
