### ISSUE TITLE
Pasting to Debian 10 CLI from Windows 10 OpenSSH connection causes Debian 10 to hardlock

### ISSUE THREAD

**Issue by Eschin** [PowerShell/openssh-portable#462]
Hello,

Hit a very strange issue today while working on a newly installed Debian 10 VM running in a VMware environment.

If I paste anything into the CLI via the OpenSSH connection, the Debian VM hardlocks, and must be rebooted.

I use Windows OpenSSH across multiple platforms, including Ubuntu and Junos, and don't see this issue anywhere else.

The issue is mostly consistent, but has shown variation;
Typically, the very moment I paste text into the Debian CLI, the system hardlocks immediately, and we must reboot the VM.

Sometimes, a few characters of the paste will show up in the terminal before the VM hard locks.

I have been able to paste exactly 1 time successfully, out of many(dozen or more) tests.  It is easily replicated.

Was running 7.7p1, but upgraded to 8.0p1 via chocolately, and still have the issue.

Was on----
PS C:\WINDOWS\system32> ssh -V
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
PS C:\WINDOWS\system32>
Now on----
PS C:\Users\clara> ssh -V
OpenSSH_for_Windows_8.0p1, LibreSSL 2.6.5
PS C:\Users\clara>

I can copy/paste just fine from the WSL(Ubuntu) OpenSSH client, without any issues.

Unfortunately, the hardlock does not generate any events in event viewer(that I can find), and no logs appear on the Debian VM... It immediately hardlocks.

The issue seems isolated to when I use OpenSSH for Win64 only...

WinVer~
Version 2004(OS Build 19041.508)

Let me know if I need to provide any further information, thanks :)

**Comment by bagajjal** [comment]
@Eschin - Is the win32-openssh ssh client is not responding or the Debian 10 VM itself not responding (even if you try to SSH/Login from a different terminal).

Based on the problem description, it seems the later where the VM is not responding.
I am not sure how this can happen as the data sent by ssh client will be read by ssh server. If there is some issue then it affects only that ssh connection but not make the VM nonresponsive.

**Comment by Eschin** [comment]
Hello @bagajjal ,

It's the Debian VM that hardlocks, and becomes non-responsive, and must be rebooted.  The win32-openssh connection simply times out on my end.

I've since tried to replicate this on two other Windows 10 systems, same versions, but still only running win32-Openssh 7.7p1... And they both paste fine to the Debian 10 VM without issues... So this must be some weird issue isolated to the Windows 10 desktop I was working on yesterday, as I only see it happen on that system...

Very odd... Wish I could figure out the root cause... Kind of crazy a paste action can hardlock a Debian 10 server, something interesting is going on there 😆 But I'm only seeing this on 1 computer out of 3... So unless there are further thoughts on this, it may not be an issue worth pursuing at this time...

EDIT: To clarify, the Debian VM completely hardlocks, so opening another SSH connection fails.  Even loading up the virtual terminal for "direct access" to the VM, shows that the system is hardlocked and non-responsive 😕

**Comment by Eschin** [comment]
I am running WSL with Windows Terminal, and simply changed my profile setting to open the connection via `wsl ssh -A username@host`, to side step the issue for now on the affected system.  The hardlock only occurs if I use the win32-openssh via powershell on that system.

**Comment by bagajjal** [comment]
@Eschin - Good to know the problem is specific to one machine.

Can you try to use other windows based ssh clients like putty / git ssh client on the problematic machine.
Just want to know if this happens with other  windows based ssh clients  as well.

**Comment by Eschin** [comment]
@bagajjal Will do 👍 

However, I'm only at my office on Wednesdays, so I'll have to test this next week, so an update will take a while :) Appreciate the assistance!

**Comment by Eschin** [comment]
Unfortunately, haven't made it back to the office yet to test this again, but it's still on my radar.  I should be at my desk to test this again next Wednesday with an update :)

**Comment by Eschin** [comment]
Hello Bagajjal,

Sorry it took so long for an update, haven't been in the office for a few weeks.

I believe this was a "virtual hardware issue".  We run these VMs in a vmWare environment(ESXi), and have noticed issues in the past with Debian/Ubuntu machines using the vmWare proprietary (and ironically recommended) "VMXNET 3" virtual NIC.  The machine actually hard locked twice on it's own randomly, and we changed the virtual NIC to a generic "E1000E" NIC, and all issues (including the ssh CLI pasting hard lock) seems to have cleared up.

So this, I believe, was an issue with the vmWare VMXNET3 proprietary NIC... Everything works fine now 👍 Very odd the pasting of text into the CLI reliably triggered the hard lock, but I'm certain the issue was with the vmWare NIC being used... I'm not a fan of vmWare for many reasons, this is just one more reason :)

Appreciate your help, and closing this issue now as a "false alarm" so to speak.
