### ISSUE TITLE
SSH ControlMaster not functional

### ISSUE THREAD

**Issue by musm** [PowerShell/openssh-portable#463]
Setting in `~/.ssh/config`
```
ControlMaster auto
ControlPath ~/.ssh/master-%r@%h:%p
```

Leads to the errors when attempting to connect to any server:

```
getsockname failed: Bad file descriptor
channel_send_open: channel 0: unexpected internal error

```

**Comment by bagajjal** [comment]
This is in our backlog https://github.com/PowerShell/Win32-OpenSSH/issues/1328.

fyi, please open a new issue at https://github.com/PowerShell/Win32-OpenSSH/issues.
This repo is only to maintain code but not for tracking issues.
