### ISSUE TITLE
SSH ForceCommand on Windows Server 2016

### ISSUE THREAD

**Issue by twadeus** [PowerShell/openssh-portable#464]
I need a Linux server to SSH into a Windows Server 2016 server with PowerShell 7 installed using key authentication. I only want the Linux server to be able to run one PowerShell script with multiple parameters passed with the SSH session. 

From the Linux server I want to run something like this.

ssh user@winserver  Value1 Value2 

On the Windows server want something like this to run.

./demoscript.ps1 " Value1" " Value2"

I have had some luck adding the command= to the 'authorized_keys' of the user. But I have not been able to pass the parameters.

Some examples of what I have tried. 

command="C:\Program Files\PowerShell\7\pwsh.exe -File C:\scripts\demoscript.ps1 %SSH_ORIGINAL_COMMAND%"ssh-rsa

command=".\demoscript.ps1 %SSH_ORIGINAL_COMMAND%"ssh-rsa

Is using the 'authorized_keys' the best way or should I be using the sshd_config file. How should I format the ForceCommand or command setting?  

Here is what I have found for linux. 
RESTRICT SSH LOGINS TO A SINGLE COMMAND
https://research.kudelskisecurity.com/2013/05/14/restrict-ssh-logins-to-a-single-command/

**Comment by bagajjal** [comment]
Please open a new issue at https://github.com/PowerShell/Win32-OpenSSH/issues.
This repo is only to maintain code but not for tracking issues.
