### ISSUE TITLE
Why do releases of this trail upstream by multiple versions?

### ISSUE THREAD

**Issue by brettfire** [PowerShell/openssh-portable#465]
Just curious....

**Comment by bagajjal** [comment]
OpenSSH comes as inbox for win10/winserver 2019. All the security patches will be serviced through windows update.
If someone explicitly download the github release then we don't have a servicing channel so we add beta flag.

fyi, please open a new issue at https://github.com/PowerShell/Win32-OpenSSH/issues.
This repo is only to maintain code but not for tracking issues.
