### ISSUE TITLE
openssh bugged on windows with user folder including Chinese-charactor

### ISSUE THREAD

**Issue by Asxcvbn** [PowerShell/openssh-portable#467]
for example, someone's username is "用户" and thus his user folder is “C:\Users\用户”， and he might run ssh.exe on his cmd or powershell to remote: user@remote. basic usage like `ssh user@remote` works, yet one cant use "-i" option to use a identity file, with error like "cannot create directory C:\\Users\\\312\21\234\132\423/.ssh"  (here the \xxxx nums are just to show the case). and with config files and valid identity key files you are still prompted to input password for the site.
and ssh-keygen cant just save key to home folder\.ssh.

**Comment by coocooman3** [comment]
FYI, for whatever reason issues for this project are tracked in another github: https://github.com/powershell/Win32-OpenSSH
I have no idea why, but all the work is done in this repo and the issues are managed in that repo. Doesn't make sense, and it's easy to miss the one sentence mentioning it on this project homepage.

**Comment by Asxcvbn** [comment]
> 
> 
> FYI, for whatever reason issues for this project are tracked in another github: https://github.com/powershell/Win32-OpenSSH
> I have no idea why, but all the work is done in this repo and the issues are managed in that repo. Doesn't make sense, and it's easy to miss the one sentence mentioning it on this project homepage.

thanks for this, and i've opened a issue in that repo.
https://github.com/PowerShell/Win32-OpenSSH/issues/1704
