### ISSUE TITLE
Is this OpenSSH for Windows fork still maintained?

### ISSUE THREAD

**Issue by noseratio** [PowerShell/openssh-portable#468]
The OpenSSH server [that comes with with Windows 10 v20H2](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse) is rather outdated: `OpenSSH_for_Windows_7.7p1`.

The latest release from the present `openssh-portable` repo is also rather old, [v8.1.0.0 from 18 Dec 2019](https://github.com/PowerShell/openssh-portable/releases/tag/v8.1.0.0).

In contrast, Git for Windows also comes with OpenSSH, and it's pretty recent: `OpenSSH_8.4p1, OpenSSL 1.1.1h  22 Sep 2020`.

What version should we choose? Is the current fork still actively maintained?

**Comment by energister** [comment]
Take a look at this [info](https://github.com/PowerShell/Win32-OpenSSH/issues/1693)
