### ISSUE TITLE
Can we get a new (and possibly non-beta-) release?

### ISSUE THREAD

**Issue by GitMensch** [PowerShell/openssh-portable#470]
The changes since the last "beta" https://github.com/PowerShell/openssh-portable/compare/v8.1.0.0...latestw_all seem relevant enough to publish a new version and as OpenSSH (likely based on work done here) is now provided for newer Windows versions from the windows features it seems that "beta" can be dropped.

**Comment by ghost** [comment]
Looking forward to a reply or feedback from the maintainers on this question.

**Comment by colemickens** [comment]
It's been a year since there's been a release? cc: @bagajjal @manojampalam  any insights?

**Comment by hummeleBop** [comment]
Is this project still maintained ?

**Comment by ghost** [comment]
> Is this project still maintained ?

Good question, wish I knew the exact answer. Although there could be a fairly useful comment in https://github.com/PowerShell/openssh-portable/issues/466#issuecomment-727404959:
> FYI, for whatever reason issues for this project are tracked in another github: [powershell/Win32-OpenSSH](https://github.com/powershell/Win32-OpenSSH)
> I have no idea why, but all the work is done in this repo and the issues are managed in that repo. Doesn't make sense, and it's easy to miss the one sentence mentioning it on this project homepage.

See also:
- https://github.com/PowerShell/Win32-OpenSSH/blob/L1-Prod/README
- https://github.com/PowerShell/openssh-portable/blob/latestw_all/README.md
- https://github.com/PowerShell/Win32-OpenSSH/wiki

So maybe it would be better to repost the question in https://github.com/PowerShell/Win32-OpenSSH/issues

**Comment by jursed** [comment]
Seems that it is indeed still maintained, see [here](https://github.com/PowerShell/Win32-OpenSSH/issues/1750#issue-825063893).

The documentation is very haphazard, which is a real shame because it's a great project. (It makes a world of difference for remote-administering Windows machines when you don't want to go down the Active Directory rabbit hole...)

**Comment by bagajjal** [comment]
All GitHub releases are marked as beta as we don't have a servicing channel to provide the security fixes.
April 2021 windows update will update windows inbox version to OpenSSH v8.1.
I'm planning to release OpenSSH V8.5 Github release in April 2021.

**Comment by GitMensch** [comment]
> April 2021 windows update will update windows inbox version to OpenSSH v8.1.
I'm planning to release OpenSSH V8.5 Github release in April 2021.

Good to know.

> All GitHub releases are marked as beta as we don't have a servicing channel to provide the security fixes.

Then just do that as everyone else that releases on GH: Make a 8.5.0 release and if you see anything needs to be fixed or security fixes are to taken over release a 8.5.1 and so on.

**Comment by maertendMSFT** [comment]
All releases on this repo are labeled as beta as there is not a proper servicing/support channel, this will likely not change.  The versions that are included in-box on Windows are the only supported versions.  If we did move the 8.x.0 -> 8.x.1 scheme, there is no denotation that states the release is unsupported, thus the beta tag in the release name.

**Comment by GitMensch** [comment]
Thanks that makes that clear, I someday have to check the wiki and README if those informations are found there and otherwise open a new issue about the "beta-documentation" (of course I'd like to have Windows OpenSSH supported also on older versions of Windows Server, but I guess that's unlikely to happen).

One thing that comes back with the changes and the upcoming release in this month: What is the intended sharing process with upstream? #471 possible would benefit of an update, too...

**Comment by bagajjal** [comment]
> Thanks that makes that clear, I someday have to check the wiki and README if those informations are found there and otherwise open a new issue about the "beta-documentation" (of course I'd like to have Windows OpenSSH supported also on older versions of Windows Server, but I guess that's unlikely to happen).
> 
Github OpenSSH releases are supported from windows 7 and up.

**Comment by GitMensch** [comment]
> Github OpenSSH releases are supported from windows 7 and up.

Yes, but those are only beta releases and the non-beta are currently not uploaded there, which means: Win7, Win2012R2 Server and others only get the "beta" versions. If you could upload the non-beta executables as a GH release (possibly before using the common update channels to serve those to the "common user") then users can subscribe to that, know that a new version is there and update their older systems or know they'll get those soon via common update.

**Comment by bagajjal** [comment]
@GitMensch - We don't have any plans to release non-beta Github releases. 
on a side note, we do have azure VM extensions (which has servicing channel) for downlevel OS versions (win 7 and above). You can download by using the below AZ CLI cmdlets,

C:> az vm extension set --publisher "Microsoft.Azure.OpenSSH" -n WindowsOpenSSH --resource-group myrg --vm-name myvm

C:> az vm open-port --resource-group myrg --name myvm --port 22

**Comment by bagajjal** [comment]
We track issues in a different repo https://github.com/PowerShell/Win32-OpenSSH/issues.
There is an existing issue at https://github.com/PowerShell/Win32-OpenSSH/issues.
