### ISSUE TITLE
Question: What is the intended sharing process with upstream?

### ISSUE THREAD

**Issue by GitMensch** [PowerShell/openssh-portable#471]
Obviously many of the code changes would be relevant to be placed upstream - is there any plan to do send PRs?
Even more obviously this repo tends to get outdated, what are the plans on pulling OpenSSH 8,1-8,4 here?

I thought to find the information in one of the repo's README or the Wiki - but had no luck with this.

**Comment by dragonwolf83** [comment]
You can see some of the efforts in merging to upstream at https://github.com/openssh/openssh-portable/pulls?q=+is%3Apr+author%3Amanojampalam+. Most notably is the large PR https://github.com/openssh/openssh-portable/pull/63 that was rejected for being too Windows specific so alot of changes were made to try to minimize impact to upstream. I haven't seen any status updates in awhile. The last update I saw was on the wiki https://github.com/PowerShell/Win32-OpenSSH/wiki/Project-Status

**Comment by bagajjal** [comment]
@GitMensch - We have a strong desire to get our changes upstream. We tried couple of times to get our changes but they got rejected as they are very specific to windows. Our priorities have changed over the time to invest in other projects.
Upstream work is in our backlog but it took a back seat for now.

**Comment by bagajjal** [comment]
We track issues in a different repo https://github.com/PowerShell/Win32-OpenSSH/issues.
Please create a new issue.

**Comment by GitMensch** [comment]
As this was a question - going on with https://github.com/PowerShell/Win32-OpenSSH/discussions/2257.
