### ISSUE TITLE
v8.1.0.0 has problem with config Include directive

### ISSUE THREAD

**Issue by tolgaulas** [PowerShell/openssh-portable#472]
**Environement** 
Windows 10 and
PS C:\WINDOWS\system32> Get-Command ssh*exe
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     ssh.exe                                            8.1.0.0    C:\Program Files\OpenSSH-Win64\ssh.exe
Application     ssh-add.exe                                        8.1.0.0    C:\Program Files\OpenSSH-Win64\ssh-add...
Application     ssh-agent.exe                                      8.1.0.0    C:\Program Files\OpenSSH-Win64\ssh-age...
Application     sshd.exe                                           8.1.0.0    C:\Program Files\OpenSSH-Win64\sshd.exe
Application     ssh-keygen.exe                                     8.1.0.0    C:\Program Files\OpenSSH-Win64\ssh-key...
Application     ssh-keyscan.exe                                    8.1.0.0    C:\Program Files\OpenSSH-Win64\ssh-key...
Application     ssh-shellhost.exe                                  8.1.0.0    C:\Program Files\OpenSSH-Win64\ssh-she...

**Configs**
C:\\Users\\auser/.ssh/config
-----------------------------
Include theinclude

C:\\Users\\auser/.ssh/theinclude
-----------------------------
Host sample_host
 HostName 127.0.0.1
 User auser
 IdentityFile ~/.ssh/somekey.pub

**Result**
C:\>ssh sample_host -vvv
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2
debug1: Reading configuration data C:\\Users\\auser/.ssh/config
debug3: C:\\Users\\auser/.ssh/config line 1: Including file C:/Users/auser/.ssh/theinclude depth 0 (parse only)
debug1: Reading configuration data C:/Users/auser/.ssh/theinclude
debug3: Failed to open file:C:/ProgramData/ssh/ssh_config error:2
debug2: resolving "sample_host" port 22
ssh: Could not resolve hostname sample_host: No such host is known.

**Comment by riverar** [comment]
Can you provide more information on what you're expecting here? It appears `sample_host` is not resolvable to an address.

**Comment by tolgaulas** [comment]
@riverar ; When we use the include directive, shouldn't the sample_host be resolved with the HostName address? It looks like it does not.

**Comment by riverar** [comment]
@tolgaulas I see now. Does this work in `.ssh/config` directly?

**Comment by tolgaulas** [comment]
@riverar Yes it works in .ssh/config directly, indeed.

**Comment by bagajjal** [comment]
Please open a new issue at https://github.com/PowerShell/Win32-OpenSSH/issues.

**Comment by riverar** [comment]
@bagajjal Can you transfer this issue instead? https://docs.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository
