### ISSUE TITLE
Question: upgrade to OpenSSH 8.4/8.4p1

### ISSUE THREAD

**Issue by felsgaertner** [PowerShell/openssh-portable#475]
Hello, 
are there any plans to upgrade the Windows SSH to [OpenSSH 8.4/8.4p1](https://www.openssh.com/txt/release-8.4) (Upstream [V_8_4_P1](https://github.com/openssh/openssh-portable/releases/tag/V_8_4_P1))?
That would be nice for users of Windows Server 2016.
Thanks.

**Comment by bagajjal** [comment]
I'm working on OpenSSH v8.4 upgrade. It's planned for the end of the month.

Please open new issues @ https://github.com/PowerShell/win32-openssh/issues
