### ISSUE TITLE
OpenSSH trying to connect to 208.95.112.1 port 80

### ISSUE THREAD

**Issue by sagecook** [PowerShell/openssh-portable#482]
My Windows 10 Firewall is setup to prevent any outgoing port 80 traffic.  Since I did that I am seeing messages like "sshd: error: connect to 208.95.112.1 port 80 failed: Permission denied" for OpenSSH->Admin in my Windows Event Viewer.

Why is openssh trying to connect to this IP address several times each minute?  Can I disable that if it isn't needed?

**Comment by impeeza** [comment]
On that IP is hosted ip-api.com an IP Geolocation API Service

**Comment by sagecook** [comment]
Okay, thanks.  I will allow it through then.

**Comment by bagajjal** [comment]
This is specific to your environment. Default sshd_config doesn't connect to any ip.
Do you have any private changes to $env:programdata\ssh\sshd_config file?
Please share sshd_config, sshd.log for further investigation.

**Comment by bagajjal** [comment]
Please open a new issue at https://github.com/PowerShell/win32-openssh with requested information.
