### ISSUE TITLE
I can't reproduce the problems that occur with the latest Windows 10.

### ISSUE THREAD

**Issue by Mine02C4** [PowerShell/openssh-portable#485]
I have a character encoding-related bug in the SSH(OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5) that ships with the latest Windows 10(Version 10.0.19042.868).
To fix this problem, I built https://github.com/PowerShell/openssh-portable/tree/v7.7.1.0 and the problem does not occur.

Which version is bundled with the product, Windows 10?

**Comment by bagajjal** [comment]
Please try [openssh v8.1](https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v8.1.0.0p1-Beta). 
If the problem still persist then please open new issue at https://github.com/PowerShell/Win32-OpenSSH/.
