### ISSUE TITLE
Provide Tab Completion through Register-ArgumentCompleter

### ISSUE THREAD

**Issue by JKamsker** [PowerShell/openssh-portable#487]
Not having to remember saved connections in .ssh\config would be awesome!

Please provide Completion through [Register-ArgumentCompleter](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/register-argumentcompleter?view=powershell-7.1)

Register-ArgumentCompleter is implemented for example in [winget](https://github.com/microsoft/winget-cli/blob/master/doc/Completion.md?WT.mc_id=-blog-scottha)

**Comment by bagajjal** [comment]
@JKamsker - Can you be more specific

**Comment by bagajjal** [comment]
Please open the issue at https://github.com/PowerShell/Win32-OpenSSH..
