### ISSUE TITLE
Sources for the official Windows version are missing

### ISSUE THREAD

**Issue by conioh** [PowerShell/openssh-portable#496]
The repo has releases and tags for 7.7.0.0, 7.7.1.0, 7.7.2.0 and then 7.9.0.0, but the binaries Windows has are of different versions:

![image](https://user-images.githubusercontent.com/10606081/113488505-46abd080-94c7-11eb-9318-414dc60a46d1.png)

![image](https://user-images.githubusercontent.com/10606081/113488649-09940e00-94c8-11eb-9b32-38e6b1c2e337.png)

`git log -S` finds "7,7,2,0" and "7.7.2.0" but not "7,7,2,1" (or "7,7,2,3") nor "7.7.2.1" (or "7.7.2.3"), so while I have the public symbols from the symbol server, I don't have the exact sources of that version. What do you propose?

**Comment by bagajjal** [comment]
@conioh  - We maintain internal repo for windows openssh versions. These are primarily used to fix security fixes and any regressions / major issues observed in the Github releases.
