### ISSUE TITLE
Is OpenSSH an SSH client?

### ISSUE THREAD

**Issue by mushlih-almubarak** [PowerShell/openssh-portable#511]
Is OpenSSH an SSH client like puTTY? And is it installed by default on windows?  Can it substitute another SSH client like puTTY and have the same/similar features? And does it work in the same way as other puTTY/ssh clients?

**Comment by bagajjal** [comment]
Win32-OpenSSH has both client and server. Client components (like ssh.exe, scp.exe, sftp.exe) comes by default on windows 10+, windows server 2019+.

**Comment by mushlih-almubarak** [comment]
> comes by default on windows 10+, windows server 2019+.

is it also in Windows 10 Home?

**Comment by bagajjal** [comment]
Yes, please refer to https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse.

fyi, the binary location is c:\windows\system32\openssh
