### ISSUE TITLE
Agent Forwarding Windows client to Windows host not working?

### ISSUE THREAD

**Issue by monil-patel** [PowerShell/openssh-portable#540]
Is agent forwarding supported when connecting from a windows client to a windows host machine ?

I tried all of the things below, but had no luck and stumbled across this comment https://github.com/PowerShell/Win32-OpenSSH/issues/1136#issuecomment-500549297 which says _Agent forwarding is not supported on the server yet, but you should be able to use the client to forward agent to a non-Windows target._

Was following these instructions from github : https://docs.github.com/en/developers/overview/using-ssh-agent-forwarding

1) used keygen to generate public/private keys and added public to github.com 
2) ssh-add "location of private key".  Can see them on client machine through ssh-add -l 
3) Test using agent 
```powershell
PS C:\Users\monil> ssh -T git@github.com
Hi monil-patel! You've successfully authenticated, but GitHub does not provide shell access.
```

4) Specified ForwardAgent in the ssh config 
```
Host my-pc
  HostName host...
  User username
  IdentityFile C:\Users\user\.ssh\id_rsa
  ForwardAgent yes

```

5) ssh to my-pc, and run ssh -T git@github.com again 

**expected**
```
# ssh session
PS C:\Users\monil> ssh -T git@github.com
Hi monil-patel! You've successfully authenticated, but GitHub does not provide shell access.
```

**received**
```
# ssh session
git@github.com: Permission denied (publickey).
```

Cant list any keys under the ssh session 
```
# ssh session
C:\Users\monil>ssh-add -l
Error connecting to agent: No such file or directory
```

**Comment by floh96** [comment]
@monil-patel  issues are tracked at https://github.com/PowerShell/Win32-OpenSSH could you open your issue there?

**Comment by monil-patel** [comment]
@floh96 opened an issue there: https://github.com/PowerShell/Win32-OpenSSH/issues/1865
