### ISSUE TITLE
Windows 11 OpenSSH version reads 8.1p2

### ISSUE THREAD

**Issue by Amondale** [PowerShell/openssh-portable#572]
As I understand, I need 8.2 or later to support FIDO2? How does one update/upgrade? Do I use this repo? If so, can it be compiled in Linux and installed in Windows 11? How? Sorry for all the Qs?

**Comment by bagajjal** [comment]
FIDO support will be there in next win32-openssh Github release, sometime this month.
It will be shipped into windows based on the windows timeline, so can't give a particular date.
