### ISSUE TITLE
OpenSSH is currently 2 versions ahead at v9.1

### ISSUE THREAD

**Issue by user8446** [PowerShell/openssh-portable#627]
### Summary of the new feature / enhancement

Hi,

Just bringing attention that OpenSSH is currently 2 versions ahead. Including in the releases are security fixes, bugfixes, and enhancements including switching scp to sftp protocol: https://www.openssh.com/releasenotes.html . Due to the quantity in the release notes I think it would be beneficial to the community to bring the fork up to v9.1 as well.

Note: [LibreSSL is also behind](https://github.com/PowerShell/LibreSSL/issues/14)

**Comment by panekj** [comment]
https://github.com/PowerShell/openssh-portable/pull/626

**Comment by user8446** [comment]
Thanks for pointing out the PR! 9.0 was done on 9/14/22, so I guess the team is behind.

**Comment by WSLUser** [comment]
Win32-OpenSSH is always behind. The fact they're only 2 releases behind is a miracle in and of itself as it used to be far more. MS just doesn't put much time into this project as it should since it doesn't bring in revenue.

**Comment by user8446** [comment]
The security patches and bug fixing alone should be enough for a tighter release schedule.

**Comment by panekj** [comment]
> The security patches and bug fixing alone should be enough for a tighter release schedule.

security patches and bugfixes are developed internally and provided no matter which OpenSSH version is latest

**Comment by user8446** [comment]
Hi @panekj I was referring to SSH, not PS. 

OpenSSHportable has not advanced since [March 22nd](https://github.com/PowerShell/openssh-portable/tags), yet OpenSSH has had [many security patches and bugfixes](https://www.openssh.com/releasenotes.html) since then. 

Since OpenSSH/SCP is used extensively by users in PS, leaving it unpatched exposes the community to vulnerabilities and bugs.

**Comment by panekj** [comment]
> I was referring to SSH, not PS.

i was referring to that too

> Since OpenSSH/SCP is used extensively by users in PS, leaving it unpatched exposes the community to vulnerabilities and bugs.

and as I said, it's patched internally, each shipped openssh version receives security updates via Windows Update

**Comment by user8446** [comment]
I just checked and at least on W10 Home the files have not changed in `C:\Windows\System32\OpenSSH` so security patches are NOT being updated outside of the releases which again is 2 versions behind.

However, can you confirm if this is different with Pro/Workstations?

**Comment by WSLUser** [comment]
He might be referring to the SSH you can install with "Optional Features" but more often users are utilizing the github, which is the better version in general. So the github release is not getting those updates. Only the built-in version is. Built-in is never updated to another release. You have to upgrade versions of Windows to bump versions of OpenSSH. At this point, you'd need Win11 to be remotely close release wise. I consider Win11 a wasted effort with no user focus at all which I will never use. I'd sooner switch to Linux.

**Comment by SteveL-MSFT** [comment]
Since OpenSSH itself expects a POSIX OS and Windows is not, it takes longer to do the merges and validate if anything broke.  As noted above, the 9.1 upstream merge was done, but other checks and compliance work needs to be completed before a GitHub release can be made (hopefully this month).  Shipping in Windows is a whole other work item and because Windows has a specific release cadence, it will always be behind.

**Comment by user8446** [comment]
Thank you for explaining!

**Comment by SynapseScribe** [comment]
is there any place where one can download newer builds than 8.9.1.0 for windows (from https://github.com/PowerShell/Win32-OpenSSH)?

**Comment by user8446** [comment]
> is there any place where one can download newer builds than 8.9.1.0 for windows (from https://github.com/PowerShell/Win32-OpenSSH)?

There is https://www.mls-software.com/opensshd.html ( Also available on Chocolatey: https://community.chocolatey.org/packages/mls-software-openssh )

**Comment by tgauth** [comment]
Closing since 9.1 was released yesterday: https://github.com/PowerShell/Win32-OpenSSH/releases/tag/v9.1.0.0p1-Beta

**Comment by user8446** [comment]
Got it and all up to date now. Thank you to you and the team!

```
PowerShell 7.3.1
PS C:\Users\#####> ssh -V
OpenSSH_for_Windows_9.1p1, LibreSSL 3.6.1
```
