### ISSUE TITLE
Early EOF errors when running git fetch over ssh

### ISSUE THREAD

**Issue by gruselglatz** [PowerShell/openssh-portable#667]
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the latest version
- [X] Search the existing issues.

### Steps to reproduce

see https://github.com/PowerShell/Win32-OpenSSH/issues/1322

### Expected behavior

```console
see https://github.com/PowerShell/Win32-OpenSSH/issues/1322
```

### Actual behavior

```console
see https://github.com/PowerShell/Win32-OpenSSH/issues/1322
```

### Error details

```console
see https://github.com/PowerShell/Win32-OpenSSH/issues/1322
```

### Environment data

```PowerShell
see https://github.com/PowerShell/Win32-OpenSSH/issues/1322
```

### Version

9.2.0.0

### Visuals

https://github.com/PowerShell/Win32-OpenSSH/issues/1322#issuecomment-1271895943

**Comment by kiates** [comment]
Ran into this issue as well when cloning a very specific internal repository.

I.E:
> ...
> fetch-pack: unexpected disconnect while reading sideband packet
> fatal: early EOF
> fatal: fetch-pack: invalid index-pack output
> ...

Don't know why it only happens on one.

Switched back to using putty/pageant instead of open-ssh/openssh-agent as described in the referenced issue to work around it.

**Comment by tgauth** [comment]
closing since https://github.com/PowerShell/openssh-portable/pull/628 has been merged
