### ISSUE TITLE
Add support for GSSAPIKeyExchange - from PowerShell/Win32-OpenSSH

### ISSUE THREAD

**Issue by joachimlindenberg** [PowerShell/openssh-portable#678]
### Summary of the new feature / enhancement

In a corporate environment mutual authentication via Kerberos is a key feature to reduce the effort for user and key management.

There is https://github.com/PowerShell/Win32-OpenSSH/issues/15 but it is unclear whether it is going to happen and whether it is still tracked in the other repo.

**Comment by maertendMSFT** [comment]
Rehydrating the original issue on the Win32-OpenSSH repo.  Closing this issue.
