### ISSUE TITLE
Is this the default OpenSSH Server on Windows

### ISSUE THREAD

**Issue by djn3m0** [PowerShell/openssh-portable#689]
### Summary of the new feature / enhancement

Hello,

I have a quick question, Is this the repository for the default OpenSSH Server that can be installed on Windows?
If not is the repository for that is available? and where can I find it?

Thanks

**Comment by maertendMSFT** [comment]
Yes, this is the repo for the in-box OpenSSH in Windows.  Code is in this repo, everything else is here: https://github.com/PowerShell/Win32-OpenSSH
